// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: changemodel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Xpilot
{

    /// <summary>Holder for reflection information generated from changemodel.proto</summary>
    public static partial class ChangemodelReflection
    {

        #region Descriptor
        /// <summary>File descriptor for changemodel.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static ChangemodelReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChFjaGFuZ2Vtb2RlbC5wcm90bxIGeHBpbG90InkKC0NoYW5nZU1vZGVsEhUK",
                  "CGNhbGxzaWduGAEgASgJSACIAQESFAoHYWlybGluZRgCIAEoCUgBiAEBEhYK",
                  "CWVxdWlwbWVudBgDIAEoCUgCiAEBQgsKCV9jYWxsc2lnbkIKCghfYWlybGlu",
                  "ZUIMCgpfZXF1aXBtZW50YgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Xpilot.ChangeModel), global::Xpilot.ChangeModel.Parser, new[]{ "Callsign", "Airline", "Equipment" }, new[]{ "Callsign", "Airline", "Equipment" }, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class ChangeModel : pb::IMessage<ChangeModel>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<ChangeModel> _parser = new pb::MessageParser<ChangeModel>(() => new ChangeModel());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ChangeModel> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Xpilot.ChangemodelReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ChangeModel()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ChangeModel(ChangeModel other) : this()
        {
            callsign_ = other.callsign_;
            airline_ = other.airline_;
            equipment_ = other.equipment_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ChangeModel Clone()
        {
            return new ChangeModel(this);
        }

        /// <summary>Field number for the "callsign" field.</summary>
        public const int CallsignFieldNumber = 1;
        private string callsign_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Callsign
        {
            get { return callsign_ ?? ""; }
            set
            {
                callsign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }
        /// <summary>Gets whether the "callsign" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasCallsign
        {
            get { return callsign_ != null; }
        }
        /// <summary>Clears the value of the "callsign" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearCallsign()
        {
            callsign_ = null;
        }

        /// <summary>Field number for the "airline" field.</summary>
        public const int AirlineFieldNumber = 2;
        private string airline_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Airline
        {
            get { return airline_ ?? ""; }
            set
            {
                airline_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }
        /// <summary>Gets whether the "airline" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasAirline
        {
            get { return airline_ != null; }
        }
        /// <summary>Clears the value of the "airline" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearAirline()
        {
            airline_ = null;
        }

        /// <summary>Field number for the "equipment" field.</summary>
        public const int EquipmentFieldNumber = 3;
        private string equipment_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Equipment
        {
            get { return equipment_ ?? ""; }
            set
            {
                equipment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }
        /// <summary>Gets whether the "equipment" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasEquipment
        {
            get { return equipment_ != null; }
        }
        /// <summary>Clears the value of the "equipment" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearEquipment()
        {
            equipment_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as ChangeModel);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ChangeModel other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Callsign != other.Callsign) return false;
            if (Airline != other.Airline) return false;
            if (Equipment != other.Equipment) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (HasCallsign) hash ^= Callsign.GetHashCode();
            if (HasAirline) hash ^= Airline.GetHashCode();
            if (HasEquipment) hash ^= Equipment.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (HasCallsign) {
        output.WriteRawTag(10);
        output.WriteString(Callsign);
      }
      if (HasAirline) {
        output.WriteRawTag(18);
        output.WriteString(Airline);
      }
      if (HasEquipment) {
        output.WriteRawTag(26);
        output.WriteString(Equipment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (HasCallsign)
            {
                output.WriteRawTag(10);
                output.WriteString(Callsign);
            }
            if (HasAirline)
            {
                output.WriteRawTag(18);
                output.WriteString(Airline);
            }
            if (HasEquipment)
            {
                output.WriteRawTag(26);
                output.WriteString(Equipment);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (HasCallsign)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Callsign);
            }
            if (HasAirline)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Airline);
            }
            if (HasEquipment)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Equipment);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ChangeModel other)
        {
            if (other == null)
            {
                return;
            }
            if (other.HasCallsign)
            {
                Callsign = other.Callsign;
            }
            if (other.HasAirline)
            {
                Airline = other.Airline;
            }
            if (other.HasEquipment)
            {
                Equipment = other.Equipment;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Callsign = input.ReadString();
            break;
          }
          case 18: {
            Airline = input.ReadString();
            break;
          }
          case 26: {
            Equipment = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Callsign = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            Airline = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            Equipment = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
