/*
 * xPilot: X-Plane pilot client for VATSIM
 * Copyright (C) 2019-2021 Justin Shannon
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
*/

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Wrapper.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Vatsim.Xpilot.Protobuf {

  /// <summary>Holder for reflection information generated from Wrapper.proto</summary>
  public static partial class WrapperReflection {

    #region Descriptor
    /// <summary>File descriptor for Wrapper.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WrapperReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1XcmFwcGVyLnByb3RvEgZ4cGlsb3QaH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8aEFhwbGFuZURhdGEucHJvdG8aF1BsdWdpbkluZm9ybWF0",
            "aW9uLnByb3RvGhNDc2xWYWxpZGF0aW9uLnByb3RvGg5BZGRQbGFuZS5wcm90",
            "bxoWQ2hhbmdlUGxhbmVNb2RlbC5wcm90bxoUUG9zaXRpb25VcGRhdGUucHJv",
            "dG8aEURlbGV0ZVBsYW5lLnByb3RvGhZOZXR3b3JrQ29ubmVjdGVkLnByb3Rv",
            "GhlOZXR3b3JrRGlzY29ubmVjdGVkLnByb3RvGhRBaXJwbGFuZUNvbmZpZy5w",
            "cm90bxoXTmVhcmJ5Q29udHJvbGxlcnMucHJvdG8aHFByaXZhdGVNZXNzYWdl",
            "UmVjZWl2ZWQucHJvdG8aGFByaXZhdGVNZXNzYWdlU2VudC5wcm90bxoUU2V0",
            "VHJhbnNwb25kZXIucHJvdG8aGEZhc3RQb3NpdGlvblVwZGF0ZS5wcm90bxoV",
            "UGxhbmVBZGRlZFRvU2ltLnByb3RvGhNTZXRSYWRpb1N0YWNrLnByb3RvGhhS",
            "ZXF1ZXN0U3RhdGlvbkluZm8ucHJvdG8aF1RyaWdnZXJEaXNjb25uZWN0LnBy",
            "b3RvIr8ICgdXcmFwcGVyEi0KCXRpbWVzdGFtcBgBIAEoCzIaLmdvb2dsZS5w",
            "cm90b2J1Zi5UaW1lc3RhbXASKQoLeHBsYW5lX2RhdGEYAiABKAsyEi54cGls",
            "b3QuWHBsYW5lRGF0YUgAEjEKD3Bvc2l0aW9uX3VwZGF0ZRgDIAEoCzIWLnhw",
            "aWxvdC5Qb3NpdGlvblVwZGF0ZUgAEjoKFGZhc3RfcG9zaXRpb25fdXBkYXRl",
            "GAQgASgLMhoueHBpbG90LkZhc3RQb3NpdGlvblVwZGF0ZUgAEjEKD2FpcnBs",
            "YW5lX2NvbmZpZxgFIAEoCzIWLnhwaWxvdC5BaXJwbGFuZUNvbmZpZ0gAEiUK",
            "CWFkZF9wbGFuZRgGIAEoCzIQLnhwaWxvdC5BZGRQbGFuZUgAEjUKEnBsYW5l",
            "X2FkZGVkX3RvX3NpbRgHIAEoCzIXLnhwaWxvdC5QbGFuZUFkZGVkVG9TaW1I",
            "ABI2ChJjaGFuZ2VfcGxhbmVfbW9kZWwYCCABKAsyGC54cGlsb3QuQ2hhbmdl",
            "UGxhbmVNb2RlbEgAEisKDGRlbGV0ZV9wbGFuZRgJIAEoCzITLnhwaWxvdC5E",
            "ZWxldGVQbGFuZUgAEkIKGHByaXZhdGVfbWVzc2FnZV9yZWNlaXZlZBgKIAEo",
            "CzIeLnhwaWxvdC5Qcml2YXRlTWVzc2FnZVJlY2VpdmVkSAASOgoUcHJpdmF0",
            "ZV9tZXNzYWdlX3NlbnQYCyABKAsyGi54cGlsb3QuUHJpdmF0ZU1lc3NhZ2VT",
            "ZW50SAASNQoRbmV0d29ya19jb25uZWN0ZWQYDCABKAsyGC54cGlsb3QuTmV0",
            "d29ya0Nvbm5lY3RlZEgAEjsKFG5ldHdvcmtfZGlzY29ubmVjdGVkGA0gASgL",
            "MhsueHBpbG90Lk5ldHdvcmtEaXNjb25uZWN0ZWRIABI3ChJuZWFyYnlfY29u",
            "dHJvbGxlcnMYDiABKAsyGS54cGlsb3QuTmVhcmJ5Q29udHJvbGxlcnNIABIx",
            "Cg9zZXRfdHJhbnNwb25kZXIYDyABKAsyFi54cGlsb3QuU2V0VHJhbnNwb25k",
            "ZXJIABIvCg5zZXRfcmFkaW9zdGFjaxgQIAEoCzIVLnhwaWxvdC5TZXRSYWRp",
            "b1N0YWNrSAASNwoScGx1Z2luX2luZm9ybWF0aW9uGBEgASgLMhkueHBpbG90",
            "LlBsdWdpbkluZm9ybWF0aW9uSAASLwoOY3NsX3ZhbGlkYXRpb24YEiABKAsy",
            "FS54cGlsb3QuQ3NsVmFsaWRhdGlvbkgAEjoKFHJlcXVlc3Rfc3RhdGlvbl9p",
            "bmZvGBMgASgLMhoueHBpbG90LlJlcXVlc3RTdGF0aW9uSW5mb0gAEjcKEnRy",
            "aWdnZXJfZGlzY29ubmVjdBgUIAEoCzIZLnhwaWxvdC5UcmlnZ2VyRGlzY29u",
            "bmVjdEgAQgUKA21zZ0IZqgIWVmF0c2ltLlhwaWxvdC5Qcm90b2J1ZmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.XplaneDataReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PluginInformationReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.CslValidationReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.AddPlaneReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.ChangePlaneModelReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PositionUpdateReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.DeletePlaneReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.NetworkConnectedReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.NetworkDisconnectedReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.AirplaneConfigReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.NearbyControllersReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PrivateMessageReceivedReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PrivateMessageSentReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.SetTransponderReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.FastPositionUpdateReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PlaneAddedToSimReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.SetRadioStackReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.RequestStationInfoReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.TriggerDisconnectReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Vatsim.Xpilot.Protobuf.Wrapper), global::Vatsim.Xpilot.Protobuf.Wrapper.Parser, new[]{ "Timestamp", "XplaneData", "PositionUpdate", "FastPositionUpdate", "AirplaneConfig", "AddPlane", "PlaneAddedToSim", "ChangePlaneModel", "DeletePlane", "PrivateMessageReceived", "PrivateMessageSent", "NetworkConnected", "NetworkDisconnected", "NearbyControllers", "SetTransponder", "SetRadiostack", "PluginInformation", "CslValidation", "RequestStationInfo", "TriggerDisconnect" }, new[]{ "Msg" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Wrapper : pb::IMessage<Wrapper>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Wrapper> _parser = new pb::MessageParser<Wrapper>(() => new Wrapper());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Wrapper> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Vatsim.Xpilot.Protobuf.WrapperReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wrapper() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wrapper(Wrapper other) : this() {
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      switch (other.MsgCase) {
        case MsgOneofCase.XplaneData:
          XplaneData = other.XplaneData.Clone();
          break;
        case MsgOneofCase.PositionUpdate:
          PositionUpdate = other.PositionUpdate.Clone();
          break;
        case MsgOneofCase.FastPositionUpdate:
          FastPositionUpdate = other.FastPositionUpdate.Clone();
          break;
        case MsgOneofCase.AirplaneConfig:
          AirplaneConfig = other.AirplaneConfig.Clone();
          break;
        case MsgOneofCase.AddPlane:
          AddPlane = other.AddPlane.Clone();
          break;
        case MsgOneofCase.PlaneAddedToSim:
          PlaneAddedToSim = other.PlaneAddedToSim.Clone();
          break;
        case MsgOneofCase.ChangePlaneModel:
          ChangePlaneModel = other.ChangePlaneModel.Clone();
          break;
        case MsgOneofCase.DeletePlane:
          DeletePlane = other.DeletePlane.Clone();
          break;
        case MsgOneofCase.PrivateMessageReceived:
          PrivateMessageReceived = other.PrivateMessageReceived.Clone();
          break;
        case MsgOneofCase.PrivateMessageSent:
          PrivateMessageSent = other.PrivateMessageSent.Clone();
          break;
        case MsgOneofCase.NetworkConnected:
          NetworkConnected = other.NetworkConnected.Clone();
          break;
        case MsgOneofCase.NetworkDisconnected:
          NetworkDisconnected = other.NetworkDisconnected.Clone();
          break;
        case MsgOneofCase.NearbyControllers:
          NearbyControllers = other.NearbyControllers.Clone();
          break;
        case MsgOneofCase.SetTransponder:
          SetTransponder = other.SetTransponder.Clone();
          break;
        case MsgOneofCase.SetRadiostack:
          SetRadiostack = other.SetRadiostack.Clone();
          break;
        case MsgOneofCase.PluginInformation:
          PluginInformation = other.PluginInformation.Clone();
          break;
        case MsgOneofCase.CslValidation:
          CslValidation = other.CslValidation.Clone();
          break;
        case MsgOneofCase.RequestStationInfo:
          RequestStationInfo = other.RequestStationInfo.Clone();
          break;
        case MsgOneofCase.TriggerDisconnect:
          TriggerDisconnect = other.TriggerDisconnect.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wrapper Clone() {
      return new Wrapper(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "xplane_data" field.</summary>
    public const int XplaneDataFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.XplaneData XplaneData {
      get { return msgCase_ == MsgOneofCase.XplaneData ? (global::Vatsim.Xpilot.Protobuf.XplaneData) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.XplaneData;
      }
    }

    /// <summary>Field number for the "position_update" field.</summary>
    public const int PositionUpdateFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PositionUpdate PositionUpdate {
      get { return msgCase_ == MsgOneofCase.PositionUpdate ? (global::Vatsim.Xpilot.Protobuf.PositionUpdate) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PositionUpdate;
      }
    }

    /// <summary>Field number for the "fast_position_update" field.</summary>
    public const int FastPositionUpdateFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.FastPositionUpdate FastPositionUpdate {
      get { return msgCase_ == MsgOneofCase.FastPositionUpdate ? (global::Vatsim.Xpilot.Protobuf.FastPositionUpdate) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.FastPositionUpdate;
      }
    }

    /// <summary>Field number for the "airplane_config" field.</summary>
    public const int AirplaneConfigFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.AirplaneConfig AirplaneConfig {
      get { return msgCase_ == MsgOneofCase.AirplaneConfig ? (global::Vatsim.Xpilot.Protobuf.AirplaneConfig) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AirplaneConfig;
      }
    }

    /// <summary>Field number for the "add_plane" field.</summary>
    public const int AddPlaneFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.AddPlane AddPlane {
      get { return msgCase_ == MsgOneofCase.AddPlane ? (global::Vatsim.Xpilot.Protobuf.AddPlane) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AddPlane;
      }
    }

    /// <summary>Field number for the "plane_added_to_sim" field.</summary>
    public const int PlaneAddedToSimFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim PlaneAddedToSim {
      get { return msgCase_ == MsgOneofCase.PlaneAddedToSim ? (global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PlaneAddedToSim;
      }
    }

    /// <summary>Field number for the "change_plane_model" field.</summary>
    public const int ChangePlaneModelFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.ChangePlaneModel ChangePlaneModel {
      get { return msgCase_ == MsgOneofCase.ChangePlaneModel ? (global::Vatsim.Xpilot.Protobuf.ChangePlaneModel) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ChangePlaneModel;
      }
    }

    /// <summary>Field number for the "delete_plane" field.</summary>
    public const int DeletePlaneFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.DeletePlane DeletePlane {
      get { return msgCase_ == MsgOneofCase.DeletePlane ? (global::Vatsim.Xpilot.Protobuf.DeletePlane) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.DeletePlane;
      }
    }

    /// <summary>Field number for the "private_message_received" field.</summary>
    public const int PrivateMessageReceivedFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived PrivateMessageReceived {
      get { return msgCase_ == MsgOneofCase.PrivateMessageReceived ? (global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PrivateMessageReceived;
      }
    }

    /// <summary>Field number for the "private_message_sent" field.</summary>
    public const int PrivateMessageSentFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PrivateMessageSent PrivateMessageSent {
      get { return msgCase_ == MsgOneofCase.PrivateMessageSent ? (global::Vatsim.Xpilot.Protobuf.PrivateMessageSent) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PrivateMessageSent;
      }
    }

    /// <summary>Field number for the "network_connected" field.</summary>
    public const int NetworkConnectedFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.NetworkConnected NetworkConnected {
      get { return msgCase_ == MsgOneofCase.NetworkConnected ? (global::Vatsim.Xpilot.Protobuf.NetworkConnected) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.NetworkConnected;
      }
    }

    /// <summary>Field number for the "network_disconnected" field.</summary>
    public const int NetworkDisconnectedFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.NetworkDisconnected NetworkDisconnected {
      get { return msgCase_ == MsgOneofCase.NetworkDisconnected ? (global::Vatsim.Xpilot.Protobuf.NetworkDisconnected) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.NetworkDisconnected;
      }
    }

    /// <summary>Field number for the "nearby_controllers" field.</summary>
    public const int NearbyControllersFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.NearbyControllers NearbyControllers {
      get { return msgCase_ == MsgOneofCase.NearbyControllers ? (global::Vatsim.Xpilot.Protobuf.NearbyControllers) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.NearbyControllers;
      }
    }

    /// <summary>Field number for the "set_transponder" field.</summary>
    public const int SetTransponderFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.SetTransponder SetTransponder {
      get { return msgCase_ == MsgOneofCase.SetTransponder ? (global::Vatsim.Xpilot.Protobuf.SetTransponder) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SetTransponder;
      }
    }

    /// <summary>Field number for the "set_radiostack" field.</summary>
    public const int SetRadiostackFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.SetRadioStack SetRadiostack {
      get { return msgCase_ == MsgOneofCase.SetRadiostack ? (global::Vatsim.Xpilot.Protobuf.SetRadioStack) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SetRadiostack;
      }
    }

    /// <summary>Field number for the "plugin_information" field.</summary>
    public const int PluginInformationFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PluginInformation PluginInformation {
      get { return msgCase_ == MsgOneofCase.PluginInformation ? (global::Vatsim.Xpilot.Protobuf.PluginInformation) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PluginInformation;
      }
    }

    /// <summary>Field number for the "csl_validation" field.</summary>
    public const int CslValidationFieldNumber = 18;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.CslValidation CslValidation {
      get { return msgCase_ == MsgOneofCase.CslValidation ? (global::Vatsim.Xpilot.Protobuf.CslValidation) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.CslValidation;
      }
    }

    /// <summary>Field number for the "request_station_info" field.</summary>
    public const int RequestStationInfoFieldNumber = 19;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.RequestStationInfo RequestStationInfo {
      get { return msgCase_ == MsgOneofCase.RequestStationInfo ? (global::Vatsim.Xpilot.Protobuf.RequestStationInfo) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.RequestStationInfo;
      }
    }

    /// <summary>Field number for the "trigger_disconnect" field.</summary>
    public const int TriggerDisconnectFieldNumber = 20;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.TriggerDisconnect TriggerDisconnect {
      get { return msgCase_ == MsgOneofCase.TriggerDisconnect ? (global::Vatsim.Xpilot.Protobuf.TriggerDisconnect) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.TriggerDisconnect;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      XplaneData = 2,
      PositionUpdate = 3,
      FastPositionUpdate = 4,
      AirplaneConfig = 5,
      AddPlane = 6,
      PlaneAddedToSim = 7,
      ChangePlaneModel = 8,
      DeletePlane = 9,
      PrivateMessageReceived = 10,
      PrivateMessageSent = 11,
      NetworkConnected = 12,
      NetworkDisconnected = 13,
      NearbyControllers = 14,
      SetTransponder = 15,
      SetRadiostack = 16,
      PluginInformation = 17,
      CslValidation = 18,
      RequestStationInfo = 19,
      TriggerDisconnect = 20,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Wrapper);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Wrapper other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (!object.Equals(XplaneData, other.XplaneData)) return false;
      if (!object.Equals(PositionUpdate, other.PositionUpdate)) return false;
      if (!object.Equals(FastPositionUpdate, other.FastPositionUpdate)) return false;
      if (!object.Equals(AirplaneConfig, other.AirplaneConfig)) return false;
      if (!object.Equals(AddPlane, other.AddPlane)) return false;
      if (!object.Equals(PlaneAddedToSim, other.PlaneAddedToSim)) return false;
      if (!object.Equals(ChangePlaneModel, other.ChangePlaneModel)) return false;
      if (!object.Equals(DeletePlane, other.DeletePlane)) return false;
      if (!object.Equals(PrivateMessageReceived, other.PrivateMessageReceived)) return false;
      if (!object.Equals(PrivateMessageSent, other.PrivateMessageSent)) return false;
      if (!object.Equals(NetworkConnected, other.NetworkConnected)) return false;
      if (!object.Equals(NetworkDisconnected, other.NetworkDisconnected)) return false;
      if (!object.Equals(NearbyControllers, other.NearbyControllers)) return false;
      if (!object.Equals(SetTransponder, other.SetTransponder)) return false;
      if (!object.Equals(SetRadiostack, other.SetRadiostack)) return false;
      if (!object.Equals(PluginInformation, other.PluginInformation)) return false;
      if (!object.Equals(CslValidation, other.CslValidation)) return false;
      if (!object.Equals(RequestStationInfo, other.RequestStationInfo)) return false;
      if (!object.Equals(TriggerDisconnect, other.TriggerDisconnect)) return false;
      if (MsgCase != other.MsgCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (msgCase_ == MsgOneofCase.XplaneData) hash ^= XplaneData.GetHashCode();
      if (msgCase_ == MsgOneofCase.PositionUpdate) hash ^= PositionUpdate.GetHashCode();
      if (msgCase_ == MsgOneofCase.FastPositionUpdate) hash ^= FastPositionUpdate.GetHashCode();
      if (msgCase_ == MsgOneofCase.AirplaneConfig) hash ^= AirplaneConfig.GetHashCode();
      if (msgCase_ == MsgOneofCase.AddPlane) hash ^= AddPlane.GetHashCode();
      if (msgCase_ == MsgOneofCase.PlaneAddedToSim) hash ^= PlaneAddedToSim.GetHashCode();
      if (msgCase_ == MsgOneofCase.ChangePlaneModel) hash ^= ChangePlaneModel.GetHashCode();
      if (msgCase_ == MsgOneofCase.DeletePlane) hash ^= DeletePlane.GetHashCode();
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) hash ^= PrivateMessageReceived.GetHashCode();
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) hash ^= PrivateMessageSent.GetHashCode();
      if (msgCase_ == MsgOneofCase.NetworkConnected) hash ^= NetworkConnected.GetHashCode();
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) hash ^= NetworkDisconnected.GetHashCode();
      if (msgCase_ == MsgOneofCase.NearbyControllers) hash ^= NearbyControllers.GetHashCode();
      if (msgCase_ == MsgOneofCase.SetTransponder) hash ^= SetTransponder.GetHashCode();
      if (msgCase_ == MsgOneofCase.SetRadiostack) hash ^= SetRadiostack.GetHashCode();
      if (msgCase_ == MsgOneofCase.PluginInformation) hash ^= PluginInformation.GetHashCode();
      if (msgCase_ == MsgOneofCase.CslValidation) hash ^= CslValidation.GetHashCode();
      if (msgCase_ == MsgOneofCase.RequestStationInfo) hash ^= RequestStationInfo.GetHashCode();
      if (msgCase_ == MsgOneofCase.TriggerDisconnect) hash ^= TriggerDisconnect.GetHashCode();
      hash ^= (int) msgCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (msgCase_ == MsgOneofCase.XplaneData) {
        output.WriteRawTag(18);
        output.WriteMessage(XplaneData);
      }
      if (msgCase_ == MsgOneofCase.PositionUpdate) {
        output.WriteRawTag(26);
        output.WriteMessage(PositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.FastPositionUpdate) {
        output.WriteRawTag(34);
        output.WriteMessage(FastPositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.AirplaneConfig) {
        output.WriteRawTag(42);
        output.WriteMessage(AirplaneConfig);
      }
      if (msgCase_ == MsgOneofCase.AddPlane) {
        output.WriteRawTag(50);
        output.WriteMessage(AddPlane);
      }
      if (msgCase_ == MsgOneofCase.PlaneAddedToSim) {
        output.WriteRawTag(58);
        output.WriteMessage(PlaneAddedToSim);
      }
      if (msgCase_ == MsgOneofCase.ChangePlaneModel) {
        output.WriteRawTag(66);
        output.WriteMessage(ChangePlaneModel);
      }
      if (msgCase_ == MsgOneofCase.DeletePlane) {
        output.WriteRawTag(74);
        output.WriteMessage(DeletePlane);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
        output.WriteRawTag(82);
        output.WriteMessage(PrivateMessageReceived);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
        output.WriteRawTag(90);
        output.WriteMessage(PrivateMessageSent);
      }
      if (msgCase_ == MsgOneofCase.NetworkConnected) {
        output.WriteRawTag(98);
        output.WriteMessage(NetworkConnected);
      }
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
        output.WriteRawTag(106);
        output.WriteMessage(NetworkDisconnected);
      }
      if (msgCase_ == MsgOneofCase.NearbyControllers) {
        output.WriteRawTag(114);
        output.WriteMessage(NearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.SetTransponder) {
        output.WriteRawTag(122);
        output.WriteMessage(SetTransponder);
      }
      if (msgCase_ == MsgOneofCase.SetRadiostack) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(SetRadiostack);
      }
      if (msgCase_ == MsgOneofCase.PluginInformation) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(PluginInformation);
      }
      if (msgCase_ == MsgOneofCase.CslValidation) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(CslValidation);
      }
      if (msgCase_ == MsgOneofCase.RequestStationInfo) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(RequestStationInfo);
      }
      if (msgCase_ == MsgOneofCase.TriggerDisconnect) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(TriggerDisconnect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (msgCase_ == MsgOneofCase.XplaneData) {
        output.WriteRawTag(18);
        output.WriteMessage(XplaneData);
      }
      if (msgCase_ == MsgOneofCase.PositionUpdate) {
        output.WriteRawTag(26);
        output.WriteMessage(PositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.FastPositionUpdate) {
        output.WriteRawTag(34);
        output.WriteMessage(FastPositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.AirplaneConfig) {
        output.WriteRawTag(42);
        output.WriteMessage(AirplaneConfig);
      }
      if (msgCase_ == MsgOneofCase.AddPlane) {
        output.WriteRawTag(50);
        output.WriteMessage(AddPlane);
      }
      if (msgCase_ == MsgOneofCase.PlaneAddedToSim) {
        output.WriteRawTag(58);
        output.WriteMessage(PlaneAddedToSim);
      }
      if (msgCase_ == MsgOneofCase.ChangePlaneModel) {
        output.WriteRawTag(66);
        output.WriteMessage(ChangePlaneModel);
      }
      if (msgCase_ == MsgOneofCase.DeletePlane) {
        output.WriteRawTag(74);
        output.WriteMessage(DeletePlane);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
        output.WriteRawTag(82);
        output.WriteMessage(PrivateMessageReceived);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
        output.WriteRawTag(90);
        output.WriteMessage(PrivateMessageSent);
      }
      if (msgCase_ == MsgOneofCase.NetworkConnected) {
        output.WriteRawTag(98);
        output.WriteMessage(NetworkConnected);
      }
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
        output.WriteRawTag(106);
        output.WriteMessage(NetworkDisconnected);
      }
      if (msgCase_ == MsgOneofCase.NearbyControllers) {
        output.WriteRawTag(114);
        output.WriteMessage(NearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.SetTransponder) {
        output.WriteRawTag(122);
        output.WriteMessage(SetTransponder);
      }
      if (msgCase_ == MsgOneofCase.SetRadiostack) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(SetRadiostack);
      }
      if (msgCase_ == MsgOneofCase.PluginInformation) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(PluginInformation);
      }
      if (msgCase_ == MsgOneofCase.CslValidation) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(CslValidation);
      }
      if (msgCase_ == MsgOneofCase.RequestStationInfo) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(RequestStationInfo);
      }
      if (msgCase_ == MsgOneofCase.TriggerDisconnect) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(TriggerDisconnect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (msgCase_ == MsgOneofCase.XplaneData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(XplaneData);
      }
      if (msgCase_ == MsgOneofCase.PositionUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.FastPositionUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FastPositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.AirplaneConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AirplaneConfig);
      }
      if (msgCase_ == MsgOneofCase.AddPlane) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddPlane);
      }
      if (msgCase_ == MsgOneofCase.PlaneAddedToSim) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlaneAddedToSim);
      }
      if (msgCase_ == MsgOneofCase.ChangePlaneModel) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangePlaneModel);
      }
      if (msgCase_ == MsgOneofCase.DeletePlane) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeletePlane);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrivateMessageReceived);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrivateMessageSent);
      }
      if (msgCase_ == MsgOneofCase.NetworkConnected) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NetworkConnected);
      }
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NetworkDisconnected);
      }
      if (msgCase_ == MsgOneofCase.NearbyControllers) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.SetTransponder) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SetTransponder);
      }
      if (msgCase_ == MsgOneofCase.SetRadiostack) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SetRadiostack);
      }
      if (msgCase_ == MsgOneofCase.PluginInformation) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PluginInformation);
      }
      if (msgCase_ == MsgOneofCase.CslValidation) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CslValidation);
      }
      if (msgCase_ == MsgOneofCase.RequestStationInfo) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RequestStationInfo);
      }
      if (msgCase_ == MsgOneofCase.TriggerDisconnect) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TriggerDisconnect);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Wrapper other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      switch (other.MsgCase) {
        case MsgOneofCase.XplaneData:
          if (XplaneData == null) {
            XplaneData = new global::Vatsim.Xpilot.Protobuf.XplaneData();
          }
          XplaneData.MergeFrom(other.XplaneData);
          break;
        case MsgOneofCase.PositionUpdate:
          if (PositionUpdate == null) {
            PositionUpdate = new global::Vatsim.Xpilot.Protobuf.PositionUpdate();
          }
          PositionUpdate.MergeFrom(other.PositionUpdate);
          break;
        case MsgOneofCase.FastPositionUpdate:
          if (FastPositionUpdate == null) {
            FastPositionUpdate = new global::Vatsim.Xpilot.Protobuf.FastPositionUpdate();
          }
          FastPositionUpdate.MergeFrom(other.FastPositionUpdate);
          break;
        case MsgOneofCase.AirplaneConfig:
          if (AirplaneConfig == null) {
            AirplaneConfig = new global::Vatsim.Xpilot.Protobuf.AirplaneConfig();
          }
          AirplaneConfig.MergeFrom(other.AirplaneConfig);
          break;
        case MsgOneofCase.AddPlane:
          if (AddPlane == null) {
            AddPlane = new global::Vatsim.Xpilot.Protobuf.AddPlane();
          }
          AddPlane.MergeFrom(other.AddPlane);
          break;
        case MsgOneofCase.PlaneAddedToSim:
          if (PlaneAddedToSim == null) {
            PlaneAddedToSim = new global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim();
          }
          PlaneAddedToSim.MergeFrom(other.PlaneAddedToSim);
          break;
        case MsgOneofCase.ChangePlaneModel:
          if (ChangePlaneModel == null) {
            ChangePlaneModel = new global::Vatsim.Xpilot.Protobuf.ChangePlaneModel();
          }
          ChangePlaneModel.MergeFrom(other.ChangePlaneModel);
          break;
        case MsgOneofCase.DeletePlane:
          if (DeletePlane == null) {
            DeletePlane = new global::Vatsim.Xpilot.Protobuf.DeletePlane();
          }
          DeletePlane.MergeFrom(other.DeletePlane);
          break;
        case MsgOneofCase.PrivateMessageReceived:
          if (PrivateMessageReceived == null) {
            PrivateMessageReceived = new global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived();
          }
          PrivateMessageReceived.MergeFrom(other.PrivateMessageReceived);
          break;
        case MsgOneofCase.PrivateMessageSent:
          if (PrivateMessageSent == null) {
            PrivateMessageSent = new global::Vatsim.Xpilot.Protobuf.PrivateMessageSent();
          }
          PrivateMessageSent.MergeFrom(other.PrivateMessageSent);
          break;
        case MsgOneofCase.NetworkConnected:
          if (NetworkConnected == null) {
            NetworkConnected = new global::Vatsim.Xpilot.Protobuf.NetworkConnected();
          }
          NetworkConnected.MergeFrom(other.NetworkConnected);
          break;
        case MsgOneofCase.NetworkDisconnected:
          if (NetworkDisconnected == null) {
            NetworkDisconnected = new global::Vatsim.Xpilot.Protobuf.NetworkDisconnected();
          }
          NetworkDisconnected.MergeFrom(other.NetworkDisconnected);
          break;
        case MsgOneofCase.NearbyControllers:
          if (NearbyControllers == null) {
            NearbyControllers = new global::Vatsim.Xpilot.Protobuf.NearbyControllers();
          }
          NearbyControllers.MergeFrom(other.NearbyControllers);
          break;
        case MsgOneofCase.SetTransponder:
          if (SetTransponder == null) {
            SetTransponder = new global::Vatsim.Xpilot.Protobuf.SetTransponder();
          }
          SetTransponder.MergeFrom(other.SetTransponder);
          break;
        case MsgOneofCase.SetRadiostack:
          if (SetRadiostack == null) {
            SetRadiostack = new global::Vatsim.Xpilot.Protobuf.SetRadioStack();
          }
          SetRadiostack.MergeFrom(other.SetRadiostack);
          break;
        case MsgOneofCase.PluginInformation:
          if (PluginInformation == null) {
            PluginInformation = new global::Vatsim.Xpilot.Protobuf.PluginInformation();
          }
          PluginInformation.MergeFrom(other.PluginInformation);
          break;
        case MsgOneofCase.CslValidation:
          if (CslValidation == null) {
            CslValidation = new global::Vatsim.Xpilot.Protobuf.CslValidation();
          }
          CslValidation.MergeFrom(other.CslValidation);
          break;
        case MsgOneofCase.RequestStationInfo:
          if (RequestStationInfo == null) {
            RequestStationInfo = new global::Vatsim.Xpilot.Protobuf.RequestStationInfo();
          }
          RequestStationInfo.MergeFrom(other.RequestStationInfo);
          break;
        case MsgOneofCase.TriggerDisconnect:
          if (TriggerDisconnect == null) {
            TriggerDisconnect = new global::Vatsim.Xpilot.Protobuf.TriggerDisconnect();
          }
          TriggerDisconnect.MergeFrom(other.TriggerDisconnect);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            global::Vatsim.Xpilot.Protobuf.XplaneData subBuilder = new global::Vatsim.Xpilot.Protobuf.XplaneData();
            if (msgCase_ == MsgOneofCase.XplaneData) {
              subBuilder.MergeFrom(XplaneData);
            }
            input.ReadMessage(subBuilder);
            XplaneData = subBuilder;
            break;
          }
          case 26: {
            global::Vatsim.Xpilot.Protobuf.PositionUpdate subBuilder = new global::Vatsim.Xpilot.Protobuf.PositionUpdate();
            if (msgCase_ == MsgOneofCase.PositionUpdate) {
              subBuilder.MergeFrom(PositionUpdate);
            }
            input.ReadMessage(subBuilder);
            PositionUpdate = subBuilder;
            break;
          }
          case 34: {
            global::Vatsim.Xpilot.Protobuf.FastPositionUpdate subBuilder = new global::Vatsim.Xpilot.Protobuf.FastPositionUpdate();
            if (msgCase_ == MsgOneofCase.FastPositionUpdate) {
              subBuilder.MergeFrom(FastPositionUpdate);
            }
            input.ReadMessage(subBuilder);
            FastPositionUpdate = subBuilder;
            break;
          }
          case 42: {
            global::Vatsim.Xpilot.Protobuf.AirplaneConfig subBuilder = new global::Vatsim.Xpilot.Protobuf.AirplaneConfig();
            if (msgCase_ == MsgOneofCase.AirplaneConfig) {
              subBuilder.MergeFrom(AirplaneConfig);
            }
            input.ReadMessage(subBuilder);
            AirplaneConfig = subBuilder;
            break;
          }
          case 50: {
            global::Vatsim.Xpilot.Protobuf.AddPlane subBuilder = new global::Vatsim.Xpilot.Protobuf.AddPlane();
            if (msgCase_ == MsgOneofCase.AddPlane) {
              subBuilder.MergeFrom(AddPlane);
            }
            input.ReadMessage(subBuilder);
            AddPlane = subBuilder;
            break;
          }
          case 58: {
            global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim subBuilder = new global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim();
            if (msgCase_ == MsgOneofCase.PlaneAddedToSim) {
              subBuilder.MergeFrom(PlaneAddedToSim);
            }
            input.ReadMessage(subBuilder);
            PlaneAddedToSim = subBuilder;
            break;
          }
          case 66: {
            global::Vatsim.Xpilot.Protobuf.ChangePlaneModel subBuilder = new global::Vatsim.Xpilot.Protobuf.ChangePlaneModel();
            if (msgCase_ == MsgOneofCase.ChangePlaneModel) {
              subBuilder.MergeFrom(ChangePlaneModel);
            }
            input.ReadMessage(subBuilder);
            ChangePlaneModel = subBuilder;
            break;
          }
          case 74: {
            global::Vatsim.Xpilot.Protobuf.DeletePlane subBuilder = new global::Vatsim.Xpilot.Protobuf.DeletePlane();
            if (msgCase_ == MsgOneofCase.DeletePlane) {
              subBuilder.MergeFrom(DeletePlane);
            }
            input.ReadMessage(subBuilder);
            DeletePlane = subBuilder;
            break;
          }
          case 82: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived();
            if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
              subBuilder.MergeFrom(PrivateMessageReceived);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageReceived = subBuilder;
            break;
          }
          case 90: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageSent subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageSent();
            if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
              subBuilder.MergeFrom(PrivateMessageSent);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageSent = subBuilder;
            break;
          }
          case 98: {
            global::Vatsim.Xpilot.Protobuf.NetworkConnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkConnected();
            if (msgCase_ == MsgOneofCase.NetworkConnected) {
              subBuilder.MergeFrom(NetworkConnected);
            }
            input.ReadMessage(subBuilder);
            NetworkConnected = subBuilder;
            break;
          }
          case 106: {
            global::Vatsim.Xpilot.Protobuf.NetworkDisconnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkDisconnected();
            if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
              subBuilder.MergeFrom(NetworkDisconnected);
            }
            input.ReadMessage(subBuilder);
            NetworkDisconnected = subBuilder;
            break;
          }
          case 114: {
            global::Vatsim.Xpilot.Protobuf.NearbyControllers subBuilder = new global::Vatsim.Xpilot.Protobuf.NearbyControllers();
            if (msgCase_ == MsgOneofCase.NearbyControllers) {
              subBuilder.MergeFrom(NearbyControllers);
            }
            input.ReadMessage(subBuilder);
            NearbyControllers = subBuilder;
            break;
          }
          case 122: {
            global::Vatsim.Xpilot.Protobuf.SetTransponder subBuilder = new global::Vatsim.Xpilot.Protobuf.SetTransponder();
            if (msgCase_ == MsgOneofCase.SetTransponder) {
              subBuilder.MergeFrom(SetTransponder);
            }
            input.ReadMessage(subBuilder);
            SetTransponder = subBuilder;
            break;
          }
          case 130: {
            global::Vatsim.Xpilot.Protobuf.SetRadioStack subBuilder = new global::Vatsim.Xpilot.Protobuf.SetRadioStack();
            if (msgCase_ == MsgOneofCase.SetRadiostack) {
              subBuilder.MergeFrom(SetRadiostack);
            }
            input.ReadMessage(subBuilder);
            SetRadiostack = subBuilder;
            break;
          }
          case 138: {
            global::Vatsim.Xpilot.Protobuf.PluginInformation subBuilder = new global::Vatsim.Xpilot.Protobuf.PluginInformation();
            if (msgCase_ == MsgOneofCase.PluginInformation) {
              subBuilder.MergeFrom(PluginInformation);
            }
            input.ReadMessage(subBuilder);
            PluginInformation = subBuilder;
            break;
          }
          case 146: {
            global::Vatsim.Xpilot.Protobuf.CslValidation subBuilder = new global::Vatsim.Xpilot.Protobuf.CslValidation();
            if (msgCase_ == MsgOneofCase.CslValidation) {
              subBuilder.MergeFrom(CslValidation);
            }
            input.ReadMessage(subBuilder);
            CslValidation = subBuilder;
            break;
          }
          case 154: {
            global::Vatsim.Xpilot.Protobuf.RequestStationInfo subBuilder = new global::Vatsim.Xpilot.Protobuf.RequestStationInfo();
            if (msgCase_ == MsgOneofCase.RequestStationInfo) {
              subBuilder.MergeFrom(RequestStationInfo);
            }
            input.ReadMessage(subBuilder);
            RequestStationInfo = subBuilder;
            break;
          }
          case 162: {
            global::Vatsim.Xpilot.Protobuf.TriggerDisconnect subBuilder = new global::Vatsim.Xpilot.Protobuf.TriggerDisconnect();
            if (msgCase_ == MsgOneofCase.TriggerDisconnect) {
              subBuilder.MergeFrom(TriggerDisconnect);
            }
            input.ReadMessage(subBuilder);
            TriggerDisconnect = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            global::Vatsim.Xpilot.Protobuf.XplaneData subBuilder = new global::Vatsim.Xpilot.Protobuf.XplaneData();
            if (msgCase_ == MsgOneofCase.XplaneData) {
              subBuilder.MergeFrom(XplaneData);
            }
            input.ReadMessage(subBuilder);
            XplaneData = subBuilder;
            break;
          }
          case 26: {
            global::Vatsim.Xpilot.Protobuf.PositionUpdate subBuilder = new global::Vatsim.Xpilot.Protobuf.PositionUpdate();
            if (msgCase_ == MsgOneofCase.PositionUpdate) {
              subBuilder.MergeFrom(PositionUpdate);
            }
            input.ReadMessage(subBuilder);
            PositionUpdate = subBuilder;
            break;
          }
          case 34: {
            global::Vatsim.Xpilot.Protobuf.FastPositionUpdate subBuilder = new global::Vatsim.Xpilot.Protobuf.FastPositionUpdate();
            if (msgCase_ == MsgOneofCase.FastPositionUpdate) {
              subBuilder.MergeFrom(FastPositionUpdate);
            }
            input.ReadMessage(subBuilder);
            FastPositionUpdate = subBuilder;
            break;
          }
          case 42: {
            global::Vatsim.Xpilot.Protobuf.AirplaneConfig subBuilder = new global::Vatsim.Xpilot.Protobuf.AirplaneConfig();
            if (msgCase_ == MsgOneofCase.AirplaneConfig) {
              subBuilder.MergeFrom(AirplaneConfig);
            }
            input.ReadMessage(subBuilder);
            AirplaneConfig = subBuilder;
            break;
          }
          case 50: {
            global::Vatsim.Xpilot.Protobuf.AddPlane subBuilder = new global::Vatsim.Xpilot.Protobuf.AddPlane();
            if (msgCase_ == MsgOneofCase.AddPlane) {
              subBuilder.MergeFrom(AddPlane);
            }
            input.ReadMessage(subBuilder);
            AddPlane = subBuilder;
            break;
          }
          case 58: {
            global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim subBuilder = new global::Vatsim.Xpilot.Protobuf.PlaneAddedToSim();
            if (msgCase_ == MsgOneofCase.PlaneAddedToSim) {
              subBuilder.MergeFrom(PlaneAddedToSim);
            }
            input.ReadMessage(subBuilder);
            PlaneAddedToSim = subBuilder;
            break;
          }
          case 66: {
            global::Vatsim.Xpilot.Protobuf.ChangePlaneModel subBuilder = new global::Vatsim.Xpilot.Protobuf.ChangePlaneModel();
            if (msgCase_ == MsgOneofCase.ChangePlaneModel) {
              subBuilder.MergeFrom(ChangePlaneModel);
            }
            input.ReadMessage(subBuilder);
            ChangePlaneModel = subBuilder;
            break;
          }
          case 74: {
            global::Vatsim.Xpilot.Protobuf.DeletePlane subBuilder = new global::Vatsim.Xpilot.Protobuf.DeletePlane();
            if (msgCase_ == MsgOneofCase.DeletePlane) {
              subBuilder.MergeFrom(DeletePlane);
            }
            input.ReadMessage(subBuilder);
            DeletePlane = subBuilder;
            break;
          }
          case 82: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived();
            if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
              subBuilder.MergeFrom(PrivateMessageReceived);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageReceived = subBuilder;
            break;
          }
          case 90: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageSent subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageSent();
            if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
              subBuilder.MergeFrom(PrivateMessageSent);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageSent = subBuilder;
            break;
          }
          case 98: {
            global::Vatsim.Xpilot.Protobuf.NetworkConnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkConnected();
            if (msgCase_ == MsgOneofCase.NetworkConnected) {
              subBuilder.MergeFrom(NetworkConnected);
            }
            input.ReadMessage(subBuilder);
            NetworkConnected = subBuilder;
            break;
          }
          case 106: {
            global::Vatsim.Xpilot.Protobuf.NetworkDisconnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkDisconnected();
            if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
              subBuilder.MergeFrom(NetworkDisconnected);
            }
            input.ReadMessage(subBuilder);
            NetworkDisconnected = subBuilder;
            break;
          }
          case 114: {
            global::Vatsim.Xpilot.Protobuf.NearbyControllers subBuilder = new global::Vatsim.Xpilot.Protobuf.NearbyControllers();
            if (msgCase_ == MsgOneofCase.NearbyControllers) {
              subBuilder.MergeFrom(NearbyControllers);
            }
            input.ReadMessage(subBuilder);
            NearbyControllers = subBuilder;
            break;
          }
          case 122: {
            global::Vatsim.Xpilot.Protobuf.SetTransponder subBuilder = new global::Vatsim.Xpilot.Protobuf.SetTransponder();
            if (msgCase_ == MsgOneofCase.SetTransponder) {
              subBuilder.MergeFrom(SetTransponder);
            }
            input.ReadMessage(subBuilder);
            SetTransponder = subBuilder;
            break;
          }
          case 130: {
            global::Vatsim.Xpilot.Protobuf.SetRadioStack subBuilder = new global::Vatsim.Xpilot.Protobuf.SetRadioStack();
            if (msgCase_ == MsgOneofCase.SetRadiostack) {
              subBuilder.MergeFrom(SetRadiostack);
            }
            input.ReadMessage(subBuilder);
            SetRadiostack = subBuilder;
            break;
          }
          case 138: {
            global::Vatsim.Xpilot.Protobuf.PluginInformation subBuilder = new global::Vatsim.Xpilot.Protobuf.PluginInformation();
            if (msgCase_ == MsgOneofCase.PluginInformation) {
              subBuilder.MergeFrom(PluginInformation);
            }
            input.ReadMessage(subBuilder);
            PluginInformation = subBuilder;
            break;
          }
          case 146: {
            global::Vatsim.Xpilot.Protobuf.CslValidation subBuilder = new global::Vatsim.Xpilot.Protobuf.CslValidation();
            if (msgCase_ == MsgOneofCase.CslValidation) {
              subBuilder.MergeFrom(CslValidation);
            }
            input.ReadMessage(subBuilder);
            CslValidation = subBuilder;
            break;
          }
          case 154: {
            global::Vatsim.Xpilot.Protobuf.RequestStationInfo subBuilder = new global::Vatsim.Xpilot.Protobuf.RequestStationInfo();
            if (msgCase_ == MsgOneofCase.RequestStationInfo) {
              subBuilder.MergeFrom(RequestStationInfo);
            }
            input.ReadMessage(subBuilder);
            RequestStationInfo = subBuilder;
            break;
          }
          case 162: {
            global::Vatsim.Xpilot.Protobuf.TriggerDisconnect subBuilder = new global::Vatsim.Xpilot.Protobuf.TriggerDisconnect();
            if (msgCase_ == MsgOneofCase.TriggerDisconnect) {
              subBuilder.MergeFrom(TriggerDisconnect);
            }
            input.ReadMessage(subBuilder);
            TriggerDisconnect = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
