// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Wrapper.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Vatsim.Xpilot.Protobuf {

  /// <summary>Holder for reflection information generated from Wrapper.proto</summary>
  public static partial class WrapperReflection {

    #region Descriptor
    /// <summary>File descriptor for Wrapper.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WrapperReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1XcmFwcGVyLnByb3RvEgZ4cGlsb3QaH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8aFFhwbGFuZURhdGFyZWZzLnByb3RvGhBQbHVnaW5IYXNo",
            "LnByb3RvGhNQbHVnaW5WZXJzaW9uLnByb3RvGhFDU0xWYWxpZGF0ZS5wcm90",
            "bxoOQWRkUGxhbmUucHJvdG8aEUNoYW5nZU1vZGVsLnByb3RvGhRQb3NpdGlv",
            "blVwZGF0ZS5wcm90bxoRUmVtb3ZlUGxhbmUucHJvdG8aFVJlbW92ZUFsbFBs",
            "YW5lcy5wcm90bxoWTmV0d29ya0Nvbm5lY3RlZC5wcm90bxoZTmV0d29ya0Rp",
            "c2Nvbm5lY3RlZC5wcm90bxoUQWlycGxhbmVDb25maWcucHJvdG8aF05lYXJi",
            "eUNvbnRyb2xsZXJzLnByb3RvGhxDbGVhck5lYXJieUNvbnRyb2xsZXJzLnBy",
            "b3RvGhxQcml2YXRlTWVzc2FnZVJlY2VpdmVkLnByb3RvGhhQcml2YXRlTWVz",
            "c2FnZVNlbnQucHJvdG8aGFNldFRyYW5zcG9uZGVyQ29kZS5wcm90byLFBwoH",
            "V3JhcHBlchItCgl0aW1lc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYu",
            "VGltZXN0YW1wEjEKD3hwbGFuZV9kYXRhcmVmcxgCIAEoCzIWLnhwaWxvdC5Y",
            "cGxhbmVEYXRhcmVmc0gAEikKC3BsdWdpbl9oYXNoGAMgASgLMhIueHBpbG90",
            "LlBsdWdpbkhhc2hIABIvCg5wbHVnaW5fdmVyc2lvbhgEIAEoCzIVLnhwaWxv",
            "dC5QbHVnaW5WZXJzaW9uSAASKwoMY3NsX3ZhbGlkYXRlGAUgASgLMhMueHBp",
            "bG90LkNzbFZhbGlkYXRlSAASJQoJYWRkX3BsYW5lGAYgASgLMhAueHBpbG90",
            "LkFkZFBsYW5lSAASKwoMY2hhbmdlX21vZGVsGAcgASgLMhMueHBpbG90LkNo",
            "YW5nZU1vZGVsSAASMQoPcG9zaXRpb25fdXBkYXRlGAggASgLMhYueHBpbG90",
            "LlBvc2l0aW9uVXBkYXRlSAASKwoMcmVtb3ZlX3BsYW5lGAkgASgLMhMueHBp",
            "bG90LlJlbW92ZVBsYW5lSAASNAoRcmVtb3ZlX2FsbF9wbGFuZXMYCiABKAsy",
            "Fy54cGlsb3QuUmVtb3ZlQWxsUGxhbmVzSAASNQoRbmV0d29ya19jb25uZWN0",
            "ZWQYCyABKAsyGC54cGlsb3QuTmV0d29ya0Nvbm5lY3RlZEgAEjsKFG5ldHdv",
            "cmtfZGlzY29ubmVjdGVkGAwgASgLMhsueHBpbG90Lk5ldHdvcmtEaXNjb25u",
            "ZWN0ZWRIABIxCg9haXJwbGFuZV9jb25maWcYDSABKAsyFi54cGlsb3QuQWly",
            "cGxhbmVDb25maWdIABI3ChJuZWFyYnlfY29udHJvbGxlcnMYDiABKAsyGS54",
            "cGlsb3QuTmVhcmJ5Q29udHJvbGxlcnNIABJCChhjbGVhcl9uZWFyYnlfY29u",
            "dHJvbGxlcnMYDyABKAsyHi54cGlsb3QuQ2xlYXJOZWFyYnlDb250cm9sbGVy",
            "c0gAEkIKGHByaXZhdGVfbWVzc2FnZV9yZWNlaXZlZBgQIAEoCzIeLnhwaWxv",
            "dC5Qcml2YXRlTWVzc2FnZVJlY2VpdmVkSAASOgoUcHJpdmF0ZV9tZXNzYWdl",
            "X3NlbnQYESABKAsyGi54cGlsb3QuUHJpdmF0ZU1lc3NhZ2VTZW50SAASOgoU",
            "c2V0X3RyYW5zcG9uZGVyX2NvZGUYEiABKAsyGi54cGlsb3QuU2V0VHJhbnNw",
            "b25kZXJDb2RlSABCBQoDbXNnQhmqAhZWYXRzaW0uWHBpbG90LlByb3RvYnVm",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.XplaneDatarefsReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PluginHashReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PluginVersionReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.CSLValidateReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.AddPlaneReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.ChangeModelReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PositionUpdateReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.RemovePlaneReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.RemoveAllPlanesReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.NetworkConnectedReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.NetworkDisconnectedReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.AirplaneConfigReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.NearbyControllersReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.ClearNearbyControllersReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PrivateMessageReceivedReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.PrivateMessageSentReflection.Descriptor, global::Vatsim.Xpilot.Protobuf.SetTransponderCodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Vatsim.Xpilot.Protobuf.Wrapper), global::Vatsim.Xpilot.Protobuf.Wrapper.Parser, new[]{ "Timestamp", "XplaneDatarefs", "PluginHash", "PluginVersion", "CslValidate", "AddPlane", "ChangeModel", "PositionUpdate", "RemovePlane", "RemoveAllPlanes", "NetworkConnected", "NetworkDisconnected", "AirplaneConfig", "NearbyControllers", "ClearNearbyControllers", "PrivateMessageReceived", "PrivateMessageSent", "SetTransponderCode" }, new[]{ "Msg" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Wrapper : pb::IMessage<Wrapper>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Wrapper> _parser = new pb::MessageParser<Wrapper>(() => new Wrapper());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Wrapper> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Vatsim.Xpilot.Protobuf.WrapperReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wrapper() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wrapper(Wrapper other) : this() {
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      switch (other.MsgCase) {
        case MsgOneofCase.XplaneDatarefs:
          XplaneDatarefs = other.XplaneDatarefs.Clone();
          break;
        case MsgOneofCase.PluginHash:
          PluginHash = other.PluginHash.Clone();
          break;
        case MsgOneofCase.PluginVersion:
          PluginVersion = other.PluginVersion.Clone();
          break;
        case MsgOneofCase.CslValidate:
          CslValidate = other.CslValidate.Clone();
          break;
        case MsgOneofCase.AddPlane:
          AddPlane = other.AddPlane.Clone();
          break;
        case MsgOneofCase.ChangeModel:
          ChangeModel = other.ChangeModel.Clone();
          break;
        case MsgOneofCase.PositionUpdate:
          PositionUpdate = other.PositionUpdate.Clone();
          break;
        case MsgOneofCase.RemovePlane:
          RemovePlane = other.RemovePlane.Clone();
          break;
        case MsgOneofCase.RemoveAllPlanes:
          RemoveAllPlanes = other.RemoveAllPlanes.Clone();
          break;
        case MsgOneofCase.NetworkConnected:
          NetworkConnected = other.NetworkConnected.Clone();
          break;
        case MsgOneofCase.NetworkDisconnected:
          NetworkDisconnected = other.NetworkDisconnected.Clone();
          break;
        case MsgOneofCase.AirplaneConfig:
          AirplaneConfig = other.AirplaneConfig.Clone();
          break;
        case MsgOneofCase.NearbyControllers:
          NearbyControllers = other.NearbyControllers.Clone();
          break;
        case MsgOneofCase.ClearNearbyControllers:
          ClearNearbyControllers = other.ClearNearbyControllers.Clone();
          break;
        case MsgOneofCase.PrivateMessageReceived:
          PrivateMessageReceived = other.PrivateMessageReceived.Clone();
          break;
        case MsgOneofCase.PrivateMessageSent:
          PrivateMessageSent = other.PrivateMessageSent.Clone();
          break;
        case MsgOneofCase.SetTransponderCode:
          SetTransponderCode = other.SetTransponderCode.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wrapper Clone() {
      return new Wrapper(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "xplane_datarefs" field.</summary>
    public const int XplaneDatarefsFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.XplaneDatarefs XplaneDatarefs {
      get { return msgCase_ == MsgOneofCase.XplaneDatarefs ? (global::Vatsim.Xpilot.Protobuf.XplaneDatarefs) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.XplaneDatarefs;
      }
    }

    /// <summary>Field number for the "plugin_hash" field.</summary>
    public const int PluginHashFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PluginHash PluginHash {
      get { return msgCase_ == MsgOneofCase.PluginHash ? (global::Vatsim.Xpilot.Protobuf.PluginHash) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PluginHash;
      }
    }

    /// <summary>Field number for the "plugin_version" field.</summary>
    public const int PluginVersionFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PluginVersion PluginVersion {
      get { return msgCase_ == MsgOneofCase.PluginVersion ? (global::Vatsim.Xpilot.Protobuf.PluginVersion) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PluginVersion;
      }
    }

    /// <summary>Field number for the "csl_validate" field.</summary>
    public const int CslValidateFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.CslValidate CslValidate {
      get { return msgCase_ == MsgOneofCase.CslValidate ? (global::Vatsim.Xpilot.Protobuf.CslValidate) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.CslValidate;
      }
    }

    /// <summary>Field number for the "add_plane" field.</summary>
    public const int AddPlaneFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.AddPlane AddPlane {
      get { return msgCase_ == MsgOneofCase.AddPlane ? (global::Vatsim.Xpilot.Protobuf.AddPlane) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AddPlane;
      }
    }

    /// <summary>Field number for the "change_model" field.</summary>
    public const int ChangeModelFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.ChangeModel ChangeModel {
      get { return msgCase_ == MsgOneofCase.ChangeModel ? (global::Vatsim.Xpilot.Protobuf.ChangeModel) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ChangeModel;
      }
    }

    /// <summary>Field number for the "position_update" field.</summary>
    public const int PositionUpdateFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PositionUpdate PositionUpdate {
      get { return msgCase_ == MsgOneofCase.PositionUpdate ? (global::Vatsim.Xpilot.Protobuf.PositionUpdate) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PositionUpdate;
      }
    }

    /// <summary>Field number for the "remove_plane" field.</summary>
    public const int RemovePlaneFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.RemovePlane RemovePlane {
      get { return msgCase_ == MsgOneofCase.RemovePlane ? (global::Vatsim.Xpilot.Protobuf.RemovePlane) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.RemovePlane;
      }
    }

    /// <summary>Field number for the "remove_all_planes" field.</summary>
    public const int RemoveAllPlanesFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes RemoveAllPlanes {
      get { return msgCase_ == MsgOneofCase.RemoveAllPlanes ? (global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.RemoveAllPlanes;
      }
    }

    /// <summary>Field number for the "network_connected" field.</summary>
    public const int NetworkConnectedFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.NetworkConnected NetworkConnected {
      get { return msgCase_ == MsgOneofCase.NetworkConnected ? (global::Vatsim.Xpilot.Protobuf.NetworkConnected) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.NetworkConnected;
      }
    }

    /// <summary>Field number for the "network_disconnected" field.</summary>
    public const int NetworkDisconnectedFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.NetworkDisconnected NetworkDisconnected {
      get { return msgCase_ == MsgOneofCase.NetworkDisconnected ? (global::Vatsim.Xpilot.Protobuf.NetworkDisconnected) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.NetworkDisconnected;
      }
    }

    /// <summary>Field number for the "airplane_config" field.</summary>
    public const int AirplaneConfigFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.AirplaneConfig AirplaneConfig {
      get { return msgCase_ == MsgOneofCase.AirplaneConfig ? (global::Vatsim.Xpilot.Protobuf.AirplaneConfig) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AirplaneConfig;
      }
    }

    /// <summary>Field number for the "nearby_controllers" field.</summary>
    public const int NearbyControllersFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.NearbyControllers NearbyControllers {
      get { return msgCase_ == MsgOneofCase.NearbyControllers ? (global::Vatsim.Xpilot.Protobuf.NearbyControllers) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.NearbyControllers;
      }
    }

    /// <summary>Field number for the "clear_nearby_controllers" field.</summary>
    public const int ClearNearbyControllersFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers ClearNearbyControllers {
      get { return msgCase_ == MsgOneofCase.ClearNearbyControllers ? (global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ClearNearbyControllers;
      }
    }

    /// <summary>Field number for the "private_message_received" field.</summary>
    public const int PrivateMessageReceivedFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived PrivateMessageReceived {
      get { return msgCase_ == MsgOneofCase.PrivateMessageReceived ? (global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PrivateMessageReceived;
      }
    }

    /// <summary>Field number for the "private_message_sent" field.</summary>
    public const int PrivateMessageSentFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.PrivateMessageSent PrivateMessageSent {
      get { return msgCase_ == MsgOneofCase.PrivateMessageSent ? (global::Vatsim.Xpilot.Protobuf.PrivateMessageSent) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PrivateMessageSent;
      }
    }

    /// <summary>Field number for the "set_transponder_code" field.</summary>
    public const int SetTransponderCodeFieldNumber = 18;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Vatsim.Xpilot.Protobuf.SetTransponderCode SetTransponderCode {
      get { return msgCase_ == MsgOneofCase.SetTransponderCode ? (global::Vatsim.Xpilot.Protobuf.SetTransponderCode) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SetTransponderCode;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      XplaneDatarefs = 2,
      PluginHash = 3,
      PluginVersion = 4,
      CslValidate = 5,
      AddPlane = 6,
      ChangeModel = 7,
      PositionUpdate = 8,
      RemovePlane = 9,
      RemoveAllPlanes = 10,
      NetworkConnected = 11,
      NetworkDisconnected = 12,
      AirplaneConfig = 13,
      NearbyControllers = 14,
      ClearNearbyControllers = 15,
      PrivateMessageReceived = 16,
      PrivateMessageSent = 17,
      SetTransponderCode = 18,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Wrapper);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Wrapper other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (!object.Equals(XplaneDatarefs, other.XplaneDatarefs)) return false;
      if (!object.Equals(PluginHash, other.PluginHash)) return false;
      if (!object.Equals(PluginVersion, other.PluginVersion)) return false;
      if (!object.Equals(CslValidate, other.CslValidate)) return false;
      if (!object.Equals(AddPlane, other.AddPlane)) return false;
      if (!object.Equals(ChangeModel, other.ChangeModel)) return false;
      if (!object.Equals(PositionUpdate, other.PositionUpdate)) return false;
      if (!object.Equals(RemovePlane, other.RemovePlane)) return false;
      if (!object.Equals(RemoveAllPlanes, other.RemoveAllPlanes)) return false;
      if (!object.Equals(NetworkConnected, other.NetworkConnected)) return false;
      if (!object.Equals(NetworkDisconnected, other.NetworkDisconnected)) return false;
      if (!object.Equals(AirplaneConfig, other.AirplaneConfig)) return false;
      if (!object.Equals(NearbyControllers, other.NearbyControllers)) return false;
      if (!object.Equals(ClearNearbyControllers, other.ClearNearbyControllers)) return false;
      if (!object.Equals(PrivateMessageReceived, other.PrivateMessageReceived)) return false;
      if (!object.Equals(PrivateMessageSent, other.PrivateMessageSent)) return false;
      if (!object.Equals(SetTransponderCode, other.SetTransponderCode)) return false;
      if (MsgCase != other.MsgCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (msgCase_ == MsgOneofCase.XplaneDatarefs) hash ^= XplaneDatarefs.GetHashCode();
      if (msgCase_ == MsgOneofCase.PluginHash) hash ^= PluginHash.GetHashCode();
      if (msgCase_ == MsgOneofCase.PluginVersion) hash ^= PluginVersion.GetHashCode();
      if (msgCase_ == MsgOneofCase.CslValidate) hash ^= CslValidate.GetHashCode();
      if (msgCase_ == MsgOneofCase.AddPlane) hash ^= AddPlane.GetHashCode();
      if (msgCase_ == MsgOneofCase.ChangeModel) hash ^= ChangeModel.GetHashCode();
      if (msgCase_ == MsgOneofCase.PositionUpdate) hash ^= PositionUpdate.GetHashCode();
      if (msgCase_ == MsgOneofCase.RemovePlane) hash ^= RemovePlane.GetHashCode();
      if (msgCase_ == MsgOneofCase.RemoveAllPlanes) hash ^= RemoveAllPlanes.GetHashCode();
      if (msgCase_ == MsgOneofCase.NetworkConnected) hash ^= NetworkConnected.GetHashCode();
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) hash ^= NetworkDisconnected.GetHashCode();
      if (msgCase_ == MsgOneofCase.AirplaneConfig) hash ^= AirplaneConfig.GetHashCode();
      if (msgCase_ == MsgOneofCase.NearbyControllers) hash ^= NearbyControllers.GetHashCode();
      if (msgCase_ == MsgOneofCase.ClearNearbyControllers) hash ^= ClearNearbyControllers.GetHashCode();
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) hash ^= PrivateMessageReceived.GetHashCode();
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) hash ^= PrivateMessageSent.GetHashCode();
      if (msgCase_ == MsgOneofCase.SetTransponderCode) hash ^= SetTransponderCode.GetHashCode();
      hash ^= (int) msgCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (msgCase_ == MsgOneofCase.XplaneDatarefs) {
        output.WriteRawTag(18);
        output.WriteMessage(XplaneDatarefs);
      }
      if (msgCase_ == MsgOneofCase.PluginHash) {
        output.WriteRawTag(26);
        output.WriteMessage(PluginHash);
      }
      if (msgCase_ == MsgOneofCase.PluginVersion) {
        output.WriteRawTag(34);
        output.WriteMessage(PluginVersion);
      }
      if (msgCase_ == MsgOneofCase.CslValidate) {
        output.WriteRawTag(42);
        output.WriteMessage(CslValidate);
      }
      if (msgCase_ == MsgOneofCase.AddPlane) {
        output.WriteRawTag(50);
        output.WriteMessage(AddPlane);
      }
      if (msgCase_ == MsgOneofCase.ChangeModel) {
        output.WriteRawTag(58);
        output.WriteMessage(ChangeModel);
      }
      if (msgCase_ == MsgOneofCase.PositionUpdate) {
        output.WriteRawTag(66);
        output.WriteMessage(PositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.RemovePlane) {
        output.WriteRawTag(74);
        output.WriteMessage(RemovePlane);
      }
      if (msgCase_ == MsgOneofCase.RemoveAllPlanes) {
        output.WriteRawTag(82);
        output.WriteMessage(RemoveAllPlanes);
      }
      if (msgCase_ == MsgOneofCase.NetworkConnected) {
        output.WriteRawTag(90);
        output.WriteMessage(NetworkConnected);
      }
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
        output.WriteRawTag(98);
        output.WriteMessage(NetworkDisconnected);
      }
      if (msgCase_ == MsgOneofCase.AirplaneConfig) {
        output.WriteRawTag(106);
        output.WriteMessage(AirplaneConfig);
      }
      if (msgCase_ == MsgOneofCase.NearbyControllers) {
        output.WriteRawTag(114);
        output.WriteMessage(NearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.ClearNearbyControllers) {
        output.WriteRawTag(122);
        output.WriteMessage(ClearNearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(PrivateMessageReceived);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(PrivateMessageSent);
      }
      if (msgCase_ == MsgOneofCase.SetTransponderCode) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(SetTransponderCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (msgCase_ == MsgOneofCase.XplaneDatarefs) {
        output.WriteRawTag(18);
        output.WriteMessage(XplaneDatarefs);
      }
      if (msgCase_ == MsgOneofCase.PluginHash) {
        output.WriteRawTag(26);
        output.WriteMessage(PluginHash);
      }
      if (msgCase_ == MsgOneofCase.PluginVersion) {
        output.WriteRawTag(34);
        output.WriteMessage(PluginVersion);
      }
      if (msgCase_ == MsgOneofCase.CslValidate) {
        output.WriteRawTag(42);
        output.WriteMessage(CslValidate);
      }
      if (msgCase_ == MsgOneofCase.AddPlane) {
        output.WriteRawTag(50);
        output.WriteMessage(AddPlane);
      }
      if (msgCase_ == MsgOneofCase.ChangeModel) {
        output.WriteRawTag(58);
        output.WriteMessage(ChangeModel);
      }
      if (msgCase_ == MsgOneofCase.PositionUpdate) {
        output.WriteRawTag(66);
        output.WriteMessage(PositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.RemovePlane) {
        output.WriteRawTag(74);
        output.WriteMessage(RemovePlane);
      }
      if (msgCase_ == MsgOneofCase.RemoveAllPlanes) {
        output.WriteRawTag(82);
        output.WriteMessage(RemoveAllPlanes);
      }
      if (msgCase_ == MsgOneofCase.NetworkConnected) {
        output.WriteRawTag(90);
        output.WriteMessage(NetworkConnected);
      }
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
        output.WriteRawTag(98);
        output.WriteMessage(NetworkDisconnected);
      }
      if (msgCase_ == MsgOneofCase.AirplaneConfig) {
        output.WriteRawTag(106);
        output.WriteMessage(AirplaneConfig);
      }
      if (msgCase_ == MsgOneofCase.NearbyControllers) {
        output.WriteRawTag(114);
        output.WriteMessage(NearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.ClearNearbyControllers) {
        output.WriteRawTag(122);
        output.WriteMessage(ClearNearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(PrivateMessageReceived);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(PrivateMessageSent);
      }
      if (msgCase_ == MsgOneofCase.SetTransponderCode) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(SetTransponderCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (msgCase_ == MsgOneofCase.XplaneDatarefs) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(XplaneDatarefs);
      }
      if (msgCase_ == MsgOneofCase.PluginHash) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PluginHash);
      }
      if (msgCase_ == MsgOneofCase.PluginVersion) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PluginVersion);
      }
      if (msgCase_ == MsgOneofCase.CslValidate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CslValidate);
      }
      if (msgCase_ == MsgOneofCase.AddPlane) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddPlane);
      }
      if (msgCase_ == MsgOneofCase.ChangeModel) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangeModel);
      }
      if (msgCase_ == MsgOneofCase.PositionUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PositionUpdate);
      }
      if (msgCase_ == MsgOneofCase.RemovePlane) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RemovePlane);
      }
      if (msgCase_ == MsgOneofCase.RemoveAllPlanes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RemoveAllPlanes);
      }
      if (msgCase_ == MsgOneofCase.NetworkConnected) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NetworkConnected);
      }
      if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NetworkDisconnected);
      }
      if (msgCase_ == MsgOneofCase.AirplaneConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AirplaneConfig);
      }
      if (msgCase_ == MsgOneofCase.NearbyControllers) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.ClearNearbyControllers) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearNearbyControllers);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PrivateMessageReceived);
      }
      if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PrivateMessageSent);
      }
      if (msgCase_ == MsgOneofCase.SetTransponderCode) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SetTransponderCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Wrapper other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      switch (other.MsgCase) {
        case MsgOneofCase.XplaneDatarefs:
          if (XplaneDatarefs == null) {
            XplaneDatarefs = new global::Vatsim.Xpilot.Protobuf.XplaneDatarefs();
          }
          XplaneDatarefs.MergeFrom(other.XplaneDatarefs);
          break;
        case MsgOneofCase.PluginHash:
          if (PluginHash == null) {
            PluginHash = new global::Vatsim.Xpilot.Protobuf.PluginHash();
          }
          PluginHash.MergeFrom(other.PluginHash);
          break;
        case MsgOneofCase.PluginVersion:
          if (PluginVersion == null) {
            PluginVersion = new global::Vatsim.Xpilot.Protobuf.PluginVersion();
          }
          PluginVersion.MergeFrom(other.PluginVersion);
          break;
        case MsgOneofCase.CslValidate:
          if (CslValidate == null) {
            CslValidate = new global::Vatsim.Xpilot.Protobuf.CslValidate();
          }
          CslValidate.MergeFrom(other.CslValidate);
          break;
        case MsgOneofCase.AddPlane:
          if (AddPlane == null) {
            AddPlane = new global::Vatsim.Xpilot.Protobuf.AddPlane();
          }
          AddPlane.MergeFrom(other.AddPlane);
          break;
        case MsgOneofCase.ChangeModel:
          if (ChangeModel == null) {
            ChangeModel = new global::Vatsim.Xpilot.Protobuf.ChangeModel();
          }
          ChangeModel.MergeFrom(other.ChangeModel);
          break;
        case MsgOneofCase.PositionUpdate:
          if (PositionUpdate == null) {
            PositionUpdate = new global::Vatsim.Xpilot.Protobuf.PositionUpdate();
          }
          PositionUpdate.MergeFrom(other.PositionUpdate);
          break;
        case MsgOneofCase.RemovePlane:
          if (RemovePlane == null) {
            RemovePlane = new global::Vatsim.Xpilot.Protobuf.RemovePlane();
          }
          RemovePlane.MergeFrom(other.RemovePlane);
          break;
        case MsgOneofCase.RemoveAllPlanes:
          if (RemoveAllPlanes == null) {
            RemoveAllPlanes = new global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes();
          }
          RemoveAllPlanes.MergeFrom(other.RemoveAllPlanes);
          break;
        case MsgOneofCase.NetworkConnected:
          if (NetworkConnected == null) {
            NetworkConnected = new global::Vatsim.Xpilot.Protobuf.NetworkConnected();
          }
          NetworkConnected.MergeFrom(other.NetworkConnected);
          break;
        case MsgOneofCase.NetworkDisconnected:
          if (NetworkDisconnected == null) {
            NetworkDisconnected = new global::Vatsim.Xpilot.Protobuf.NetworkDisconnected();
          }
          NetworkDisconnected.MergeFrom(other.NetworkDisconnected);
          break;
        case MsgOneofCase.AirplaneConfig:
          if (AirplaneConfig == null) {
            AirplaneConfig = new global::Vatsim.Xpilot.Protobuf.AirplaneConfig();
          }
          AirplaneConfig.MergeFrom(other.AirplaneConfig);
          break;
        case MsgOneofCase.NearbyControllers:
          if (NearbyControllers == null) {
            NearbyControllers = new global::Vatsim.Xpilot.Protobuf.NearbyControllers();
          }
          NearbyControllers.MergeFrom(other.NearbyControllers);
          break;
        case MsgOneofCase.ClearNearbyControllers:
          if (ClearNearbyControllers == null) {
            ClearNearbyControllers = new global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers();
          }
          ClearNearbyControllers.MergeFrom(other.ClearNearbyControllers);
          break;
        case MsgOneofCase.PrivateMessageReceived:
          if (PrivateMessageReceived == null) {
            PrivateMessageReceived = new global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived();
          }
          PrivateMessageReceived.MergeFrom(other.PrivateMessageReceived);
          break;
        case MsgOneofCase.PrivateMessageSent:
          if (PrivateMessageSent == null) {
            PrivateMessageSent = new global::Vatsim.Xpilot.Protobuf.PrivateMessageSent();
          }
          PrivateMessageSent.MergeFrom(other.PrivateMessageSent);
          break;
        case MsgOneofCase.SetTransponderCode:
          if (SetTransponderCode == null) {
            SetTransponderCode = new global::Vatsim.Xpilot.Protobuf.SetTransponderCode();
          }
          SetTransponderCode.MergeFrom(other.SetTransponderCode);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            global::Vatsim.Xpilot.Protobuf.XplaneDatarefs subBuilder = new global::Vatsim.Xpilot.Protobuf.XplaneDatarefs();
            if (msgCase_ == MsgOneofCase.XplaneDatarefs) {
              subBuilder.MergeFrom(XplaneDatarefs);
            }
            input.ReadMessage(subBuilder);
            XplaneDatarefs = subBuilder;
            break;
          }
          case 26: {
            global::Vatsim.Xpilot.Protobuf.PluginHash subBuilder = new global::Vatsim.Xpilot.Protobuf.PluginHash();
            if (msgCase_ == MsgOneofCase.PluginHash) {
              subBuilder.MergeFrom(PluginHash);
            }
            input.ReadMessage(subBuilder);
            PluginHash = subBuilder;
            break;
          }
          case 34: {
            global::Vatsim.Xpilot.Protobuf.PluginVersion subBuilder = new global::Vatsim.Xpilot.Protobuf.PluginVersion();
            if (msgCase_ == MsgOneofCase.PluginVersion) {
              subBuilder.MergeFrom(PluginVersion);
            }
            input.ReadMessage(subBuilder);
            PluginVersion = subBuilder;
            break;
          }
          case 42: {
            global::Vatsim.Xpilot.Protobuf.CslValidate subBuilder = new global::Vatsim.Xpilot.Protobuf.CslValidate();
            if (msgCase_ == MsgOneofCase.CslValidate) {
              subBuilder.MergeFrom(CslValidate);
            }
            input.ReadMessage(subBuilder);
            CslValidate = subBuilder;
            break;
          }
          case 50: {
            global::Vatsim.Xpilot.Protobuf.AddPlane subBuilder = new global::Vatsim.Xpilot.Protobuf.AddPlane();
            if (msgCase_ == MsgOneofCase.AddPlane) {
              subBuilder.MergeFrom(AddPlane);
            }
            input.ReadMessage(subBuilder);
            AddPlane = subBuilder;
            break;
          }
          case 58: {
            global::Vatsim.Xpilot.Protobuf.ChangeModel subBuilder = new global::Vatsim.Xpilot.Protobuf.ChangeModel();
            if (msgCase_ == MsgOneofCase.ChangeModel) {
              subBuilder.MergeFrom(ChangeModel);
            }
            input.ReadMessage(subBuilder);
            ChangeModel = subBuilder;
            break;
          }
          case 66: {
            global::Vatsim.Xpilot.Protobuf.PositionUpdate subBuilder = new global::Vatsim.Xpilot.Protobuf.PositionUpdate();
            if (msgCase_ == MsgOneofCase.PositionUpdate) {
              subBuilder.MergeFrom(PositionUpdate);
            }
            input.ReadMessage(subBuilder);
            PositionUpdate = subBuilder;
            break;
          }
          case 74: {
            global::Vatsim.Xpilot.Protobuf.RemovePlane subBuilder = new global::Vatsim.Xpilot.Protobuf.RemovePlane();
            if (msgCase_ == MsgOneofCase.RemovePlane) {
              subBuilder.MergeFrom(RemovePlane);
            }
            input.ReadMessage(subBuilder);
            RemovePlane = subBuilder;
            break;
          }
          case 82: {
            global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes subBuilder = new global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes();
            if (msgCase_ == MsgOneofCase.RemoveAllPlanes) {
              subBuilder.MergeFrom(RemoveAllPlanes);
            }
            input.ReadMessage(subBuilder);
            RemoveAllPlanes = subBuilder;
            break;
          }
          case 90: {
            global::Vatsim.Xpilot.Protobuf.NetworkConnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkConnected();
            if (msgCase_ == MsgOneofCase.NetworkConnected) {
              subBuilder.MergeFrom(NetworkConnected);
            }
            input.ReadMessage(subBuilder);
            NetworkConnected = subBuilder;
            break;
          }
          case 98: {
            global::Vatsim.Xpilot.Protobuf.NetworkDisconnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkDisconnected();
            if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
              subBuilder.MergeFrom(NetworkDisconnected);
            }
            input.ReadMessage(subBuilder);
            NetworkDisconnected = subBuilder;
            break;
          }
          case 106: {
            global::Vatsim.Xpilot.Protobuf.AirplaneConfig subBuilder = new global::Vatsim.Xpilot.Protobuf.AirplaneConfig();
            if (msgCase_ == MsgOneofCase.AirplaneConfig) {
              subBuilder.MergeFrom(AirplaneConfig);
            }
            input.ReadMessage(subBuilder);
            AirplaneConfig = subBuilder;
            break;
          }
          case 114: {
            global::Vatsim.Xpilot.Protobuf.NearbyControllers subBuilder = new global::Vatsim.Xpilot.Protobuf.NearbyControllers();
            if (msgCase_ == MsgOneofCase.NearbyControllers) {
              subBuilder.MergeFrom(NearbyControllers);
            }
            input.ReadMessage(subBuilder);
            NearbyControllers = subBuilder;
            break;
          }
          case 122: {
            global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers subBuilder = new global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers();
            if (msgCase_ == MsgOneofCase.ClearNearbyControllers) {
              subBuilder.MergeFrom(ClearNearbyControllers);
            }
            input.ReadMessage(subBuilder);
            ClearNearbyControllers = subBuilder;
            break;
          }
          case 130: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived();
            if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
              subBuilder.MergeFrom(PrivateMessageReceived);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageReceived = subBuilder;
            break;
          }
          case 138: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageSent subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageSent();
            if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
              subBuilder.MergeFrom(PrivateMessageSent);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageSent = subBuilder;
            break;
          }
          case 146: {
            global::Vatsim.Xpilot.Protobuf.SetTransponderCode subBuilder = new global::Vatsim.Xpilot.Protobuf.SetTransponderCode();
            if (msgCase_ == MsgOneofCase.SetTransponderCode) {
              subBuilder.MergeFrom(SetTransponderCode);
            }
            input.ReadMessage(subBuilder);
            SetTransponderCode = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            global::Vatsim.Xpilot.Protobuf.XplaneDatarefs subBuilder = new global::Vatsim.Xpilot.Protobuf.XplaneDatarefs();
            if (msgCase_ == MsgOneofCase.XplaneDatarefs) {
              subBuilder.MergeFrom(XplaneDatarefs);
            }
            input.ReadMessage(subBuilder);
            XplaneDatarefs = subBuilder;
            break;
          }
          case 26: {
            global::Vatsim.Xpilot.Protobuf.PluginHash subBuilder = new global::Vatsim.Xpilot.Protobuf.PluginHash();
            if (msgCase_ == MsgOneofCase.PluginHash) {
              subBuilder.MergeFrom(PluginHash);
            }
            input.ReadMessage(subBuilder);
            PluginHash = subBuilder;
            break;
          }
          case 34: {
            global::Vatsim.Xpilot.Protobuf.PluginVersion subBuilder = new global::Vatsim.Xpilot.Protobuf.PluginVersion();
            if (msgCase_ == MsgOneofCase.PluginVersion) {
              subBuilder.MergeFrom(PluginVersion);
            }
            input.ReadMessage(subBuilder);
            PluginVersion = subBuilder;
            break;
          }
          case 42: {
            global::Vatsim.Xpilot.Protobuf.CslValidate subBuilder = new global::Vatsim.Xpilot.Protobuf.CslValidate();
            if (msgCase_ == MsgOneofCase.CslValidate) {
              subBuilder.MergeFrom(CslValidate);
            }
            input.ReadMessage(subBuilder);
            CslValidate = subBuilder;
            break;
          }
          case 50: {
            global::Vatsim.Xpilot.Protobuf.AddPlane subBuilder = new global::Vatsim.Xpilot.Protobuf.AddPlane();
            if (msgCase_ == MsgOneofCase.AddPlane) {
              subBuilder.MergeFrom(AddPlane);
            }
            input.ReadMessage(subBuilder);
            AddPlane = subBuilder;
            break;
          }
          case 58: {
            global::Vatsim.Xpilot.Protobuf.ChangeModel subBuilder = new global::Vatsim.Xpilot.Protobuf.ChangeModel();
            if (msgCase_ == MsgOneofCase.ChangeModel) {
              subBuilder.MergeFrom(ChangeModel);
            }
            input.ReadMessage(subBuilder);
            ChangeModel = subBuilder;
            break;
          }
          case 66: {
            global::Vatsim.Xpilot.Protobuf.PositionUpdate subBuilder = new global::Vatsim.Xpilot.Protobuf.PositionUpdate();
            if (msgCase_ == MsgOneofCase.PositionUpdate) {
              subBuilder.MergeFrom(PositionUpdate);
            }
            input.ReadMessage(subBuilder);
            PositionUpdate = subBuilder;
            break;
          }
          case 74: {
            global::Vatsim.Xpilot.Protobuf.RemovePlane subBuilder = new global::Vatsim.Xpilot.Protobuf.RemovePlane();
            if (msgCase_ == MsgOneofCase.RemovePlane) {
              subBuilder.MergeFrom(RemovePlane);
            }
            input.ReadMessage(subBuilder);
            RemovePlane = subBuilder;
            break;
          }
          case 82: {
            global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes subBuilder = new global::Vatsim.Xpilot.Protobuf.RemoveAllPlanes();
            if (msgCase_ == MsgOneofCase.RemoveAllPlanes) {
              subBuilder.MergeFrom(RemoveAllPlanes);
            }
            input.ReadMessage(subBuilder);
            RemoveAllPlanes = subBuilder;
            break;
          }
          case 90: {
            global::Vatsim.Xpilot.Protobuf.NetworkConnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkConnected();
            if (msgCase_ == MsgOneofCase.NetworkConnected) {
              subBuilder.MergeFrom(NetworkConnected);
            }
            input.ReadMessage(subBuilder);
            NetworkConnected = subBuilder;
            break;
          }
          case 98: {
            global::Vatsim.Xpilot.Protobuf.NetworkDisconnected subBuilder = new global::Vatsim.Xpilot.Protobuf.NetworkDisconnected();
            if (msgCase_ == MsgOneofCase.NetworkDisconnected) {
              subBuilder.MergeFrom(NetworkDisconnected);
            }
            input.ReadMessage(subBuilder);
            NetworkDisconnected = subBuilder;
            break;
          }
          case 106: {
            global::Vatsim.Xpilot.Protobuf.AirplaneConfig subBuilder = new global::Vatsim.Xpilot.Protobuf.AirplaneConfig();
            if (msgCase_ == MsgOneofCase.AirplaneConfig) {
              subBuilder.MergeFrom(AirplaneConfig);
            }
            input.ReadMessage(subBuilder);
            AirplaneConfig = subBuilder;
            break;
          }
          case 114: {
            global::Vatsim.Xpilot.Protobuf.NearbyControllers subBuilder = new global::Vatsim.Xpilot.Protobuf.NearbyControllers();
            if (msgCase_ == MsgOneofCase.NearbyControllers) {
              subBuilder.MergeFrom(NearbyControllers);
            }
            input.ReadMessage(subBuilder);
            NearbyControllers = subBuilder;
            break;
          }
          case 122: {
            global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers subBuilder = new global::Vatsim.Xpilot.Protobuf.ClearNearbyControllers();
            if (msgCase_ == MsgOneofCase.ClearNearbyControllers) {
              subBuilder.MergeFrom(ClearNearbyControllers);
            }
            input.ReadMessage(subBuilder);
            ClearNearbyControllers = subBuilder;
            break;
          }
          case 130: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageReceived();
            if (msgCase_ == MsgOneofCase.PrivateMessageReceived) {
              subBuilder.MergeFrom(PrivateMessageReceived);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageReceived = subBuilder;
            break;
          }
          case 138: {
            global::Vatsim.Xpilot.Protobuf.PrivateMessageSent subBuilder = new global::Vatsim.Xpilot.Protobuf.PrivateMessageSent();
            if (msgCase_ == MsgOneofCase.PrivateMessageSent) {
              subBuilder.MergeFrom(PrivateMessageSent);
            }
            input.ReadMessage(subBuilder);
            PrivateMessageSent = subBuilder;
            break;
          }
          case 146: {
            global::Vatsim.Xpilot.Protobuf.SetTransponderCode subBuilder = new global::Vatsim.Xpilot.Protobuf.SetTransponderCode();
            if (msgCase_ == MsgOneofCase.SetTransponderCode) {
              subBuilder.MergeFrom(SetTransponderCode);
            }
            input.ReadMessage(subBuilder);
            SetTransponderCode = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
